apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-gitops
  namespace: tanzu-continuousdelivery-resources
spec:
  interval: 10m0s
  path: clusters/${cluster_name}
  prune: true
  sourceRef:
    kind: GitRepository
    namespace: tanzu-continuousdelivery-resources
    name: infra-gitops